version: 1.8.1

groups:
  default:
    env-file: .env
    vars:
      sugar_run: kxgr run --group $ENV --services web
      sugar_run_rm: kxgr run --group $ENV --services web --extras=--rm

    targets:
      # DEVELOPMENT
      runserver:
        help: Run Django server on localhost
        run: |
          python src/manage.py runserver

      containers-build:
        help: Build containers
        run: |
          kxgr build --group $ENV
          kxgr up --group $ENV --options "--no-start"

      containers-start:
        help: Start all containers
        run: |
          kxgr start --group $ENV

      containers-exec:
        help:
        run: |
          kxgr exec --group $ENV --services {{ args.service }}

      containers-stop:
        help: Start all containers
        run: |
          kxgr stop --group $ENV

  django:
    targets:
      create-superuser:
        args:
          email:
            help: Specify the username
            type: string
            required: True
          username:
            help: Specify the username
            type: string
            required: True
          password:
            help: Specify the password
            type: string
            required: True
        env:
          POSTGRES_HOST: localhost
        help: create an admin user
        run: |
          export DJANGO_SUPERUSER_PASSWORD={{ args.password }}
          export DJANGO_SUPERUSER_USERNAME={{ args.username }}
          python ./src/manage.py createsuperuser --noinput --email {{ args.email }}

      migrate:
        help: Migrate regarding to the current migration files
        env-file: .env
        run: |
          python src/manage.py migrate

  dev:
    targets:
      dotenv:
        help: Configure .env file
        run: |
          python contrib/scripts/do_dotenv.py

      psql-conf:
        help: Configure postgresq.conf file
        run: |
          python contrib/scripts/do_psqlconf.py
