name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
env:
  ENV: "dev" 

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.9"]
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        mamba-version: "*"
        environment-file: conda/base.yaml
        channels: conda-forge,nodefaults
        activate-environment: mosqlimate
        use-mamba: true
        miniforge-variant: Mambaforge

    - name: Install dependencies
      run: |
        poetry lock
        poetry install

    - name: Linting
      run: |
        pre-commit install
        pre-commit run --all-files

    
    # TODO remove it
    - name: Setup tmate session
      if: "${{ failure() }}"
      uses: mxschmitt/action-tmate@v3
